//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextSender {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextSender.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 后台执行自动搜索, 搜索到的终端会加入网络列表. 的本地化字符串。
        /// </summary>
        internal static string back_auto_search {
            get {
                return ResourceManager.GetString("back_auto_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有设定切换间隔时间, 设为 0 关闭定时切换 的本地化字符串。
        /// </summary>
        internal static string backimage_loop {
            get {
                return ResourceManager.GetString("backimage_loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,使用相同分辨率的图片显示效果最好 的本地化字符串。
        /// </summary>
        internal static string best_res {
            get {
                return ResourceManager.GetString("best_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除? 的本地化字符串。
        /// </summary>
        internal static string do_delete {
            get {
                return ResourceManager.GetString("do_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有重名场景, 请修改场景名称! 的本地化字符串。
        /// </summary>
        internal static string had_name {
            get {
                return ResourceManager.GetString("had_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片框分辨率为: 的本地化字符串。
        /// </summary>
        internal static string img_res {
            get {
                return ResourceManager.GetString("img_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少需要设定一张图片! 的本地化字符串。
        /// </summary>
        internal static string need_one_img {
            get {
                return ResourceManager.GetString("need_one_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少需要设定一个视频文件 的本地化字符串。
        /// </summary>
        internal static string need_one_video {
            get {
                return ResourceManager.GetString("need_one_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有设置场景轮播时间 , 设为 0 关闭场景轮播 的本地化字符串。
        /// </summary>
        internal static string no_set_scene_loop {
            get {
                return ResourceManager.GetString("no_set_scene_loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有插入USB, 文件将保存到桌面! 的本地化字符串。
        /// </summary>
        internal static string no_usb {
            get {
                return ResourceManager.GetString("no_usb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先勾选需要接收数据的终端 的本地化字符串。
        /// </summary>
        internal static string not_select_box {
            get {
                return ResourceManager.GetString("not_select_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        internal static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名失败! 的本地化字符串。
        /// </summary>
        internal static string rename_fail {
            get {
                return ResourceManager.GetString("rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名选定场景: 的本地化字符串。
        /// </summary>
        internal static string rename_scene {
            get {
                return ResourceManager.GetString("rename_scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率 的本地化字符串。
        /// </summary>
        internal static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入场景轮流播放间隔(单位 秒)\n如果不需要轮流播放, 请设置为 0 的本地化字符串。
        /// </summary>
        internal static string scene_loop {
            get {
                return ResourceManager.GetString("scene_loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有重名场景, 是否覆盖? 的本地化字符串。
        /// </summary>
        internal static string scene_over_wr {
            get {
                return ResourceManager.GetString("scene_over_wr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕分辨率为: 的本地化字符串。
        /// </summary>
        internal static string screen_res {
            get {
                return ResourceManager.GetString("screen_res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择要发送的场景! 的本地化字符串。
        /// </summary>
        internal static string sel_scene_first {
            get {
                return ResourceManager.GetString("sel_scene_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string select_file {
            get {
                return ResourceManager.GetString("select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一张或多张图片 的本地化字符串。
        /// </summary>
        internal static string select_img_dlg {
            get {
                return ResourceManager.GetString("select_img_dlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送到选中终端? 的本地化字符串。
        /// </summary>
        internal static string send_to_box {
            get {
                return ResourceManager.GetString("send_to_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定 的本地化字符串。
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为终端设定一个名称 的本地化字符串。
        /// </summary>
        internal static string set_box_name {
            get {
                return ResourceManager.GetString("set_box_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为终端设定一个数字ID (1- 255 之间) 的本地化字符串。
        /// </summary>
        internal static string set_id {
            get {
                return ResourceManager.GetString("set_id", resourceCulture);
            }
        }
    }
}
